messages:
  help:
    - "&8&m--------------------------------"
    - "&r         &6&lRandomEvents &8- &7Help"
    - "&r"
    - "&e/randomevents help"
    - "&7Displays this help menu"
    - "&e/randomevents score [player]"
    - "&7Check your (or a specified player's) current score in an ongoing event"
    - "&e/randomevents startevent <event>"
    - "&7Manually starts a new event, given that there isn't one ongoing"
    - "&e/randomevents stopevent"
    - "&7Manually ends an ongoing event"
    - "&e/randomevents reload"
    - "&7Reloads the plugin's config"
    - "&8&m--------------------------------"