messages:
  help:
    - "&8&m--------------------------------"
    - "&r         &6&lAutoMinigames &8- &7Help"
    - "&r"
    - "&e/autominigames help"
    - "&7Displays this help menu"
    - "&e/autominigames score [player]"
    - "&7Check your (or a specified player's) current score in an ongoing event"
    - "&e/autominigames startevent <event>"
    - "&7Manually starts a new event, given that there isn't one ongoing"
    - "&e/autominigames stopevent"
    - "&7Manually ends an ongoing event"
    - "&e/autominigames reload"
    - "&7Reloads the plugin's config"
    - "&8&m--------------------------------"