name: AutoMinigames
api-version: 1.17
author: therbz
version: ALPHA-0.0.1
main: me.therbz.autominigames.AutoMinigames
softdepend: [PlaceHolderAPI]
commands:
  autominigames:
    usage: /autominigames <help | [startevent <event> <seconds>] | stopevent>
    description: Main plugin command
    aliases: [revents]
permissions:
  autominigames.user:
    description: Allows the user to participate in and execute basic user commands
    children:
      autominigames.admin: true
  autominigames.admin:
    description: Allows high-level admin commands to be used